db:
  host: localhost
  port: 3307
  user: 'root'
  password: 'root'
  database: 'traiding'
table:
  name: 'lites'
  prepare: |
    DROP TABLE IF EXISTS lites;
    CREATE TABLE IF NOT EXISTS `currencytab` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `Time` TIMESTAMP NOT NULL,
      `Open` DECIMAL(18, 10) NULL,
      `High` DECIMAL(18, 10) NULL,
      `Low` DECIMAL(18, 10) NULL,
      `Close` DECIMAL(18, 10) NOT NULL,
      `Volume` DOUBLE NULL,
      `Trades` DOUBLE NULL,
      PRIMARY KEY (`id`),
      INDEX `TIME` (`Time` ASC))
    ENGINE = InnoDB;
    COMMIT;
preferences:
  ignorefirst: 2
  separator: ','
  batch_size: 5000
mapping:
  - Time:
      idx: 1
      timeformat: '%Y-%m-%d %I-%p'
  - Symbol: 2
  - Open: 3
  - High: 4
  - Low: 5
  - Close: 6
  - VolumeLTC: 7
  - VolumeKRW: 8
